version: "3"

services:


  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      retries: 5
      start_period: 60s
      timeout: 5s
    ports:
      - "3306:3306"

  app:
    image: anosov01/itmo_bigdata_lab3
    container_name: app
    build:
      context: .
      args:
        BUCKET_KEY_ID: ${BUCKET_KEY_ID}
        BUCKET_KEY: ${BUCKET_KEY}
        REGION: ${REGION}
        VAULT_PASSWORD: ${VAULT_PASSWORD}
    ports:
      - '8000:8000'
    command: bash -c "sleep 60 && alembic upgrade head && pytest tests/test.py &&  pytest ../tests/test.py & uvicorn main:app --host 0.0.0.0 --port 8000"
    depends_on:
      mysql:
        condition: service_healthy